const {chromium}=require('playwright');
const express=require('express'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
(async()=>{
 const app=express();app.use(express.static(process.cwd()));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/js/core/context.js',r=>r.fulfill({contentType:'text/javascript',body:'window.aguardarContexto=async()=>({empresa_id:"company"});'}));
  await page.route('**/js/core/permissions.js',r=>r.fulfill({contentType:'text/javascript',body:'window.EasyLocPermissions={load:async()=>{}};window.hasPermission=()=>true;'}));
  await page.route('**/js/core/supabase.js',r=>r.fulfill({contentType:'text/javascript',body:`window.testCalls=[];window.balance=20;window.supabaseClient={rpc:async(name,args)=>{window.testCalls.push({name,args});if(name==='creditos_adicionar')window.balance+=args.p_quantidade;return {data:name==='creditos_painel'?{clientes:[{id:'kelly',nome:'Kelly Khawam',saldo:window.balance}],custos:{tecido:1,render:2,planta:3,layout:4},historico:[]}:name==='catalogo_creditos_saldo'?{saldo:window.balance,custos:{tecido:1,render:2,planta:3,layout:4},historico:[]}:null}},functions:{invoke:async(name,options)=>{window.testCalls.push({name,options});return {data:{ok:true}}}}};`}));
  await page.goto(base+'/Modulos/Comercial/CreditosIA/creditos-ia.html');await page.locator('[data-client]').click();await page.locator('#amount').fill('50');await page.locator('#add').click();await page.waitForFunction(()=>document.getElementById('total').textContent==='70');
  await page.locator('[name=render]').fill('5');await page.locator('#save-prices').click();await page.waitForFunction(()=>window.testCalls.some(c=>c.name==='creditos_definir_custos'));assert.equal(await page.evaluate(()=>window.testCalls.find(c=>c.name==='creditos_definir_custos').args.p_custos.render),5);
  await page.screenshot({path:path.join(os.tmpdir(),'chiavari-creditos-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(os.tmpdir(),'chiavari-creditos-mobile.png'),fullPage:true});
  await page.evaluate(()=>{sessionStorage.setItem('catalogo_token','test');const user=document.createElement('div');user.id='catalogUser';document.body.appendChild(user);});
  await page.addStyleTag({content:fs.readFileSync('Modulos/Comercial/Catalogo/catalogo-creditos.css','utf8')});await page.addScriptTag({content:fs.readFileSync('Modulos/Comercial/Catalogo/catalogo-creditos.js','utf8')});await page.locator('#catalogCreditBalance').waitFor();
  await page.evaluate(()=>{window.creditResult=null;window.CatalogCredits.invoke('studio-ai-engine',{body:{catalog_token:'test',scene:{}}}).then(r=>window.creditResult={ok:r.data?.ok,error:r.error?.message});});await page.locator('.catalog-credit-dialog [value=cancel]').last().click();await page.waitForFunction(()=>window.creditResult);assert.equal(await page.evaluate(()=>testCalls.filter(c=>c.name==='studio-ai-engine').length),0);
  await page.evaluate(()=>{window.CatalogCredits.invoke('studio-ai-engine',{body:{catalog_token:'test',scene:{}}});});await page.locator('.catalog-credit-dialog [value=confirm]').click();await page.waitForFunction(()=>testCalls.some(c=>c.name==='studio-ai-engine'));assert.equal(await page.evaluate(()=>testCalls.find(c=>c.name==='studio-ai-engine').options.body.expected_cost),2);
  await page.evaluate(()=>{window.balance=0;window.CatalogCredits.invoke('studio-ai-engine',{body:{catalog_token:'test',scene:{}}});});await page.locator('.catalog-credit-dialog').waitFor();assert.equal(await page.locator('.catalog-credit-dialog [value=confirm]').count(),0);await page.screenshot({path:path.join(os.tmpdir(),'chiavari-creditos-insuficientes.png')});await page.locator('.catalog-credit-dialog [value=cancel]').last().click();assert.deepEqual(errors,[]);console.log('PASS: recarga, custos, mobile, cancelamento, confirmação e saldo insuficiente');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
