(async function(){
  'use strict';
  const $=id=>document.getElementById(id),client=window.supabaseClient;
  const names={tecido:'Personalizar tecido',render:'Renderizar ambiente',planta:'Analisar planta',layout:'Planejar decoração'};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let context,data,editable=false,selected,requestId,busy=false;
  async function rpc(name,args={}){const r=await client.rpc(name,{p_empresa:context.empresa_id,...args});if(r.error)throw new Error(r.error.message);return r.data;}
  function notice(message,success=false){$('notice').textContent=message;$('notice').className=success?'success':'';}
  function clients(){const q=$('search').value.trim().toLocaleLowerCase('pt-BR');$('clients').innerHTML=data.clientes.filter(c=>(c.nome||'').toLocaleLowerCase('pt-BR').includes(q)).map(c=>`<div class="client-row"><span class="client-avatar" aria-hidden="true">${esc((c.nome||'C').slice(0,2).toUpperCase())}</span><div class="client-name"><strong>${esc(c.nome)}</strong><small>${c.saldo.toLocaleString('pt-BR')} créditos disponíveis</small></div>${editable?`<button class="btn btn-secondary" data-client="${esc(c.id)}">Adicionar créditos</button>`:''}</div>`).join('')||'<p>Nenhum decorador encontrado. O cliente precisa ter acesso ao catálogo cadastrado.</p>';}
  async function load(){data=await rpc('creditos_painel');$('total').textContent=data.clientes.reduce((sum,c)=>sum+c.saldo,0).toLocaleString('pt-BR');$('count').textContent=data.clientes.length;clients();$('price-fields').innerHTML=Object.entries(names).map(([k,n])=>`<label class="price-row">${n}<input aria-label="Custo: ${n}" name="${k}" type="number" step="1" min="0" max="100000" required value="${data.custos[k]}" ${editable?'':'disabled'}></label>`).join('');$('save-prices').hidden=!editable;$('history').innerHTML=data.historico.map(m=>`<tr><td>${new Date(m.created_at).toLocaleString('pt-BR')}</td><td>${esc(m.nome)}</td><td>${esc(m.tipo==='recarga'?'Recarga':names[m.recurso])}</td><td>${m.tipo==='recarga'?'+':m.status==='estornado'?'↩':'−'}${m.quantidade}</td><td><span class="status ${m.status==='reservado'?'pending':''}">${m.status==='estornado'?'Devolvido':m.status==='reservado'?'Em processamento':'Concluído'}</span></td><td>${esc(m.nota)}</td></tr>`).join('')||'<tr><td colspan="6">As movimentações aparecerão aqui.</td></tr>';}
  $('search').addEventListener('input',()=>data&&clients());
  $('refresh').onclick=async()=>{try{await load();notice('Dados atualizados.',true);}catch(e){notice(e.message);}};
  $('clients').onclick=e=>{const b=e.target.closest('[data-client]');if(!b||!editable)return;selected=data.clientes.find(c=>c.id===b.dataset.client);requestId=crypto.randomUUID();$('recharge-title').textContent=selected.nome;$('recharge-balance').textContent=`Saldo atual: ${selected.saldo} créditos`;$('recharge-error').textContent='';$('amount').value=100;$('note').value='';$('recharge').showModal();};
  $('cancel').onclick=()=>{if(!busy)$('recharge').close();};$('recharge').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
  document.querySelectorAll('[data-amount]').forEach(b=>b.onclick=()=>{$('amount').value=b.dataset.amount;});
  $('recharge-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('add').disabled=true;$('cancel').disabled=true;try{await rpc('creditos_adicionar',{p_cliente:selected.id,p_quantidade:Number($('amount').value),p_nota:$('note').value.trim(),p_id:requestId});$('recharge').close();notice('Créditos adicionados com sucesso.',true);await load();}catch(e){$('recharge-error').textContent=e.message;notice(e.message);}finally{busy=false;$('add').disabled=false;$('cancel').disabled=false;}};
  $('prices').onsubmit=async e=>{e.preventDefault();$('save-prices').disabled=true;try{const prices=Object.fromEntries(new FormData(e.target).entries());for(const k in prices)prices[k]=Number(prices[k]);await rpc('creditos_definir_custos',{p_custos:prices});notice('Custos atualizados. Os clientes confirmarão os novos valores antes de usar a IA.',true);}catch(e){notice(e.message);}finally{$('save-prices').disabled=false;}};
  try{context=await window.aguardarContexto();await window.EasyLocPermissions.load();if(!window.hasPermission('comercial.creditos.visualizar'))throw new Error('Você não tem permissão para consultar créditos.');editable=window.hasPermission('comercial.creditos.editar');await load();}catch(e){notice(e.message);$('prices').hidden=true;}
})();
